<a href="https://colab.research.google.com/github/LukeRDuob/AI-Labsheets/blob/main/L2_Lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lab 2: Intro to Neural Networks


**Q1**



In [24]:
import torch as t
import numpy as np

# Define tensors
W_1 = t.tensor([[1., 0., 1., 0., 1.],[0., 1., 1., 1., 0.],[1., 0., 0., 1., 1.]])
W_2 = t.tensor([[1., 0., 0.], [0., 1., -1.], [0., 0., 1.]])
b_1 = t.tensor([-1., 0., 0.])
b_2 = t.tensor([1., 0., -1.])
x = t.tensor([1., 2., 1., 2., 1.])

# Compute the first-layer linear output
a = W_1@x + b_1
print(a)


tensor([2., 5., 4.])


**Q2**

In [25]:
# Compute values for hidden layer
h = t.relu(a)
print(h)

tensor([2., 5., 4.])


**Q3**

In [26]:
# Compute Logits
z = W_2@h + b_2
print(z)

tensor([3., 1., 3.])


**Q4**

In [27]:
# Compute softmax probabilities
p = t.exp(z)/t.sum(t.exp(z))
print(p)


tensor([0.4683, 0.0634, 0.4683])


**Q5**

In [28]:
L = - t.log(p[2])
print(L)

tensor(0.7586)
